import About from "@/components/About";
import Catering from "@/components/Catering";
import Connect from "@/components/Connect";
import FeaturedItems from "@/components/FeaturedItems";
import FindUs from "@/components/FindUs";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import NavBar from "@/components/NavBar";
import Title from "@/components/Title";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cuba Bakery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <div className="flex flex-col min-h-screen">
        <NavBar />
        <main className="flex-grow">
          {/* container after NavBar */}
          <div className="w-full flex flex-col items-center gap-10 mb-10 pt-20">
            <Hero />
            <Title />
            <About />
            <Catering />
            <FeaturedItems />
            <Connect />
            <FindUs />
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
}

